run.sh: 31: run.sh: ./predict_from_file.py: Permission denied
